# Параметры видео по умолчанию
DEFAULT_FPS = 30.0

# Параметры трекера
MOG2_HISTORY = 500
MOG2_VAR_THRESHOLD = 50
MOG2_DETECT_SHADOWS = False
MORPH_KERNEL_SIZE = (3, 3)
MIN_CONTOUR_AREA = 20

# Цвета
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

# Параметры визуализации
TRAJECTORY_LENGTH = 50
CIRCLE_COLOR = RED  # красный
CIRCLE_RADIUS = 4
LINE_COORDINATES_COLOR = GREEN    # зелёный
LINE_THICKNESS = 1
TEXT_PERIOD_COLOR = WHITE  # белый
TEXT_COORDINATES_SCALE = 0.5
TEXT_COORDINATES_COLOR = WHITE
TEXT_COORDINATES_THICKNESS = 1
TEXT_X_DISTANCE = 10
TEXT_Y_DISTANCE = 10
TEXT_PERIOD_SIZE = 1
TEXT_PERIOD_THICKNESS = 2
X_POSITION_PERIOD = 20
Y_POSITION_PERIOD = 40
DRAW_TRAJECTORY = True # Рисовать ли траекторию?

# Данные
THE_AMOUNT_OF_DATA_REQUIRED_FOR_ANALYSIS = 2
AMOUNT_OF_DATA_REQUIRED_TO_CALCULATE_THE_PERIOD = 10

# Параметры окна
WINDOW_NAME = 'Tracking'
WAIT_KEY_DELAY = 30
ESC_KEY_CODE = 27


# Путь к видео
VIDEO_PATH = "source/videos/object2.mp4"